# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87ba909649e90f4de10b73f45b6d6d987f03b12aaceba6c0868e28ca91440b38c51c39bcc8352247afb2de4cf6ecec85e0750b01c3565cd7b5f2c128b7556cfa

test:
  secret_key_base: 04dbd475aa394a61287754e1aab0fb5e71a1ef602c96c37aa18defd8c3602d329d113c91eed493488ce2272bc03674e949b6de65603d461c7efdfa092e936553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
